### ISSUE TITLE
IATI standard version not showing in the metadata on the Registry

### ISSUE THREAD

**Issue by PetyaKangalova** [IATI/ckanext-iati#117] opened 2017-03-28 09:50 UTC
@pmartignoli @chrisviderum 

We have just been contacted by a publisher notifying us that the IATI standard version is not showing in their metadata on the Registry. The version has been correctly identified in their XML file. See an example in here: https://www.iatiregistry.org/dataset/pwc-activities

This seems to be an issue affecting other publishers as well. Could you please investigate and fix accordingly?

**Comment by dalepotter** [comment] 2017-03-28 10:16
Investigations by @hayfield have found that there is a config file specified in https://github.com/ViderumGlobal/ckanext-iati/commit/e9a35c7bbdadfa98eac97fad89b45f45deda4d3e which stores a list of allowed versions. This may be relevant.

If the config file does not exist a global variable is used - see https://github.com/ViderumGlobal/ckanext-iati/blob/master/ckanext/iati/archiver.py#L190-L194  

I have submitted a pull request to update this fallback with the current versions of the Standard (i..e adding `1.05` and `2.02`): https://github.com/ViderumGlobal/ckanext-iati/pull/116 

However, I suspect that this is not the root of the issue, since there is an example of a DfID file (published at 2.01) which also experiences this bug: https://iatiregistry.org/dataset/dfid-af

**Comment by chrisviderum** [comment] 2017-03-28 11:54
Hey @dalepotter ,

thank you for your message.

Just to double check, the standard version in the meta data looks like this:

<iati-organisations generated-datetime="2014-09-10T07:15:37Z" version="2.02">
 


(Found on http://iatistandard.org/202/organisation-standard/example-xml/ )


If yes, I can confirm that this is missing at the beginning of the file. @pmartignoli will forward your pull request to our team and let them review it and investigate, if further steps are needed.

Best regards,

Chris

**Comment by dalepotter** [comment] 2017-03-31 09:47
Hi @chrisviderum 

Just following up on this one - yes the `version` attribute would appear witin the root `<iati-organisations>` element as part of an IATI **organisation file** - for example: https://github.com/IATI/IATI-Extra-Documentation/blob/version-2.02/en/organisation-standard/organisation-standard-example-annotated.xml#L4  The documentation for this is [here](http://iatistandard.org/202/activity-standard/iati-activities/#attributes).

Furthermore, the `version` attribute can also appear witin the root `<iati-activities>` element as part of an IATI **activity file** - for example: https://github.com/IATI/IATI-Extra-Documentation/blob/version-2.02/en/activity-standard/activity-standard-example-annotated.xml#L4 The documentation for this is [here](http://iatistandard.org/202/organisation-standard/iati-organisations/#attributes).

**Comment by JGulic** [comment] 2017-05-08 15:32
Hi @dalepotter ,

I've made some changes to the code and pushed it to staging iati portal, and I've left it through the weekend so I can check if it works correctly. The version is now saved and displayed. Since everything is ok we can push this to production tomorrow.

**Comment by pmartignoli** [comment] 2017-05-22 11:30
@dalepotter, the IATI standard version was not being saved because the data_dict value for extra values such as the iati_standard_version was set to empty. When the iati_standard_version existed in the XML file, the data was being overridden with an empty value which is why it wasn't being updated. 

Changes have been made to not override the extras in the data_dictionary and the iati_standard_version is now being saved on production.

**Comment by dalepotter** [comment] 2017-06-02 09:41
Thanks for this update @pmartignoli and great that this is deployed to production. As such, I will now close this issue.

**Comment by dalepotter** [comment] 2017-06-23 13:55
I have been looking at the British Red Cross dataset [BRC Grants to partners](https://iatiregistry.org/dataset/gb-chc-220949-activities), which is also experiencing this issue. This may be linked to #125.

The Registry metadata shows `IATI Standard Version: -`:

![image](https://user-images.githubusercontent.com/8247168/27485171-9f34e7bc-5823-11e7-84b1-a0f994907d19.png)

However the data contained within the file shows `version="2.01"`:
![image](https://user-images.githubusercontent.com/8247168/27485199-be80283e-5823-11e7-85f3-8da319ca45a5.png)

My understanding is that the nightly harvester script should update this element of metadata field, based upon the data contained with the dataset itself.

**Comment by newkdukem** [comment] 2017-07-19 17:07
@JGulic fix is working, however there are some datasets that are not affected by the fix (194 of them, to be exact). As in #125 we are investigating this and already have a list of possible culprits.

**Comment by newkdukem** [comment] 2017-09-29 13:17
A postmortem report: the iati-archiver which is responsible for updating the metadata (in this case, the "IATI Standard Version") was working properly. However, the schema was not properly updated in [plugins.py](https://github.com/ViderumGlobal/ckanext-iati/blob/master/ckanext/iati/plugins.py), causing to leave the field blank when modified via web. 
The fix is currently on the [staging portal](http://iati-staging.ckan.io), and the iati-archiver was manually run in order to update the fields accordingly.

**Comment by andylolz** [comment] 2017-10-04 14:50
It looks like the `iati.standard_versions` config setting that’s referenced here:
https://github.com/ViderumGlobal/ckanext-iati/blob/f6539246169597e874cf0e4ade83e2268724a2fd/ckanext/iati/archiver.py#L191

…needs to be updated to include 1.01 and 2.02 – all datasets that use these versions are currently being marked as “n/a” in the `iati_version` metadata. (Alternatively, if you remove the setting completely, the default defined here looks correct:
https://github.com/ViderumGlobal/ckanext-iati/blob/f6539246169597e874cf0e4ade83e2268724a2fd/ckanext/iati/lists.py#L3-L5
For reference, a complete list of valid IATI versions is available here:
http://iatistandard.org/202/codelists/Version/

Apart from that, this checks out.

**Comment by amy-silcock** [comment] 2017-10-04 15:37
Great @andylolz , thanks for looking into this! @newkdukem and Viderum would you be able to follow up on this please?

**Comment by JGulic** [comment] 2017-10-18 15:14
The configuration file on the staging portal contains the correct IATI version's that are available in the link. The changes to iati.standard_versions on the staging portal were made and deployed along with the changes for the IATI Standard Version metadata code changes.
@dalepotter @amy-silcock we would need your approval in order to push these changes to production

**Comment by dalepotter** [comment] 2017-10-23 12:13
@JGulic yes let's deploy to production.

**Comment by JGulic** [comment] 2017-10-30 09:42
@dalepotter the code has been deployed to production, successfully ran this weekend and updated the standard version to the resources that didn't had the correct one.
Let us know if everything is ok, so we can close this issue

**Comment by andylolz** [comment] 2017-10-30 11:04
There’s a bunch that are still wrong. Here’s a list (but note that the dataset data used here is a few days out of date).

dataset version | registry version | dataset URL | dataset name
----------------|------------------|----------|-------------
1.03 | n/a | https://iatiregistry.org/dataset/af-14 | af-14
1.03 | n/a | https://iatiregistry.org/dataset/ics-41188664 | ics-41188664
1.03 | n/a | https://iatiregistry.org/dataset/ics-org | ics-org
1.03 | n/a | https://iatiregistry.org/dataset/kpmgea-org | kpmgea-org
1.03 | n/a | https://iatiregistry.org/dataset/ofid-activity1 | ofid-activity1
1.03 | n/a | https://iatiregistry.org/dataset/simone_sympany-org | simone_sympany-org
1.04 | n/a | https://iatiregistry.org/dataset/uasd-dataset | uasd-dataset
1.04 | n/a | https://iatiregistry.org/dataset/unesco-org | unesco-org
1.04 | None | https://iatiregistry.org/dataset/ec-devco-ec | ec-devco-ec
1.04 | None | https://iatiregistry.org/dataset/ec-near-189 | ec-near-189
1.04 | None | https://iatiregistry.org/dataset/ec-near-298 | ec-near-298
1.04 | None | https://iatiregistry.org/dataset/ec-near-589 | ec-near-589
1.04 | None | https://iatiregistry.org/dataset/ec-near-619 | ec-near-619
1.04 | None | https://iatiregistry.org/dataset/ec-near-689 | ec-near-689
1.04 | None | https://iatiregistry.org/dataset/ec-near-798 | ec-near-798
1.04 | None | https://iatiregistry.org/dataset/ec-near-88 | ec-near-88
1.04 | None | https://iatiregistry.org/dataset/ec-near-89 | ec-near-89
1.04 | None | https://iatiregistry.org/dataset/ec-near-998 | ec-near-998
1.04 | None | https://iatiregistry.org/dataset/ec-near-af | ec-near-af
1.04 | None | https://iatiregistry.org/dataset/ec-near-al | ec-near-al
1.04 | None | https://iatiregistry.org/dataset/ec-near-am | ec-near-am
1.04 | None | https://iatiregistry.org/dataset/ec-near-az | ec-near-az
1.04 | None | https://iatiregistry.org/dataset/ec-near-ba | ec-near-ba
1.04 | None | https://iatiregistry.org/dataset/ec-near-bg | ec-near-bg
1.04 | None | https://iatiregistry.org/dataset/ec-near-by | ec-near-by
1.04 | None | https://iatiregistry.org/dataset/ec-near-cz | ec-near-cz
1.04 | None | https://iatiregistry.org/dataset/ec-near-dz | ec-near-dz
1.04 | None | https://iatiregistry.org/dataset/ec-near-eg | ec-near-eg
1.04 | None | https://iatiregistry.org/dataset/ec-near-ge | ec-near-ge
1.04 | None | https://iatiregistry.org/dataset/ec-near-hr | ec-near-hr
1.04 | None | https://iatiregistry.org/dataset/ec-near-hu | ec-near-hu
1.04 | None | https://iatiregistry.org/dataset/ec-near-il | ec-near-il
1.04 | None | https://iatiregistry.org/dataset/ec-near-iq | ec-near-iq
1.04 | None | https://iatiregistry.org/dataset/ec-near-is | ec-near-is
1.04 | None | https://iatiregistry.org/dataset/ec-near-jo | ec-near-jo
1.04 | None | https://iatiregistry.org/dataset/ec-near-kz | ec-near-kz
1.04 | None | https://iatiregistry.org/dataset/ec-near-lb | ec-near-lb
1.04 | None | https://iatiregistry.org/dataset/ec-near-lt | ec-near-lt
1.04 | None | https://iatiregistry.org/dataset/ec-near-ly | ec-near-ly
1.04 | None | https://iatiregistry.org/dataset/ec-near-ma | ec-near-ma
1.04 | None | https://iatiregistry.org/dataset/ec-near-md | ec-near-md
1.04 | None | https://iatiregistry.org/dataset/ec-near-me | ec-near-me
1.04 | None | https://iatiregistry.org/dataset/ec-near-mk | ec-near-mk
1.04 | None | https://iatiregistry.org/dataset/ec-near-ps | ec-near-ps
1.04 | None | https://iatiregistry.org/dataset/ec-near-ro | ec-near-ro
1.04 | None | https://iatiregistry.org/dataset/ec-near-rs | ec-near-rs
1.04 | None | https://iatiregistry.org/dataset/ec-near-ru | ec-near-ru
1.04 | None | https://iatiregistry.org/dataset/ec-near-sk | ec-near-sk
1.04 | None | https://iatiregistry.org/dataset/ec-near-sy | ec-near-sy
1.04 | None | https://iatiregistry.org/dataset/ec-near-tn | ec-near-tn
1.04 | None | https://iatiregistry.org/dataset/ec-near-tr | ec-near-tr
1.04 | None | https://iatiregistry.org/dataset/ec-near-ua | ec-near-ua
1.04 | None | https://iatiregistry.org/dataset/ec-near-xk | ec-near-xk
1.05 | n/a | https://iatiregistry.org/dataset/bmub_iki-998 | bmub_iki-998
2.01 | 2.02 | https://iatiregistry.org/dataset/mlf-activities | mlf-activities
2.01 | n/a | https://iatiregistry.org/dataset/sida-org | sida-org
2.01 | None | https://iatiregistry.org/dataset/gac-amc-act_2_3 | gac-amc-act_2_3
2.01 | None | https://iatiregistry.org/dataset/said-org | said-org
2.02 | n/a | https://iatiregistry.org/dataset/achest-org | achest-org
2.02 | n/a | https://iatiregistry.org/dataset/dance4life-org | dance4life-org
2.02 | n/a | https://iatiregistry.org/dataset/friendsofpwyf-activities2 | friendsofpwyf-activities2
2.02 | n/a | https://iatiregistry.org/dataset/fwf-org | fwf-org
2.02 | n/a | https://iatiregistry.org/dataset/ieu-4105 | ieu-4105
2.02 | n/a | https://iatiregistry.org/dataset/max-foundation-org | max-foundation-org
2.02 | n/a | https://iatiregistry.org/dataset/utz-org | utz-org
2.02 | None | https://iatiregistry.org/dataset/alcrer-1-org | alcrer-1-org
2.02 | None | https://iatiregistry.org/dataset/bracintl-activities | bracintl-activities
2.02 | None | https://iatiregistry.org/dataset/cocnl_publisher-activities | cocnl_publisher-activities
2.02 | None | https://iatiregistry.org/dataset/creausa-org-activities | creausa-org-activities
2.02 | None | https://iatiregistry.org/dataset/fmo-7001_disclosure_overview | fmo-7001_disclosure_overview
2.02 | None | https://iatiregistry.org/dataset/freeagirl-bd | freeagirl-bd
2.02 | None | https://iatiregistry.org/dataset/freeagirl-in | freeagirl-in
2.02 | None | https://iatiregistry.org/dataset/freeagirl-nl | freeagirl-nl
2.02 | None | https://iatiregistry.org/dataset/freeagirl-th | freeagirl-th
2.02 | None | https://iatiregistry.org/dataset/nl-kvk-54436222-27541-nl | nl-kvk-54436222-27541-nl

**Comment by JGulic** [comment] 2017-10-30 13:51
@andylolz I've added reasons why the archiver failed in the cases

dataset version | registry version | dataset URL | dataset name | Reason for fail of archiver
-- | -- | -- | -- | --
1.03 | n/a | https://iatiregistry.org/dataset/af-14 | af-14 | Wrong file type
1.03 | n/a | https://iatiregistry.org/dataset/ics-41188664 | ics-41188664 | Wrong file type
1.03 | n/a | https://iatiregistry.org/dataset/ics-org | ics-org | Wrong file type
1.03 | n/a | https://iatiregistry.org/dataset/kpmgea-org | kpmgea-org | Wrong file type
1.03 | n/a | https://iatiregistry.org/dataset/ofid-activity1 | ofid-activity1 | Wrong file type
1.03 | n/a | https://iatiregistry.org/dataset/simone_sympany-org | simone_sympany-org | Wrong file type
1.04 | n/a | https://iatiregistry.org/dataset/uasd-dataset | uasd-dataset | Wrong file type
1.04 | n/a | https://iatiregistry.org/dataset/unesco-org | unesco-org | Wrong file type
1.04 | None | https://iatiregistry.org/dataset/ec-devco-ec | ec-devco-ec | Validation error
1.04 | None | https://iatiregistry.org/dataset/ec-near-189 | ec-near-189 | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-298 | ec-near-298 | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-589 | ec-near-589 | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-619 | ec-near-619 | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-689 | ec-near-689 | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-798 | ec-near-798 | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-88 | ec-near-88 | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-89 | ec-near-89 | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-998 | ec-near-998 | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-af | ec-near-af | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-al | ec-near-al | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-am | ec-near-am | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-az | ec-near-az | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-ba | ec-near-ba | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-bg | ec-near-bg | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-by | ec-near-by | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-cz | ec-near-cz | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-dz | ec-near-dz | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-eg | ec-near-eg | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-ge | ec-near-ge | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-hr | ec-near-hr | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-hu | ec-near-hu | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-il | ec-near-il | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-iq | ec-near-iq | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-is | ec-near-is | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-jo | ec-near-jo | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-kz | ec-near-kz | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-lb | ec-near-lb | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-lt | ec-near-lt | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-ly | ec-near-ly | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-ma | ec-near-ma | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-md | ec-near-md | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-me | ec-near-me | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-mk | ec-near-mk | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-ps | ec-near-ps | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-ro | ec-near-ro | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-rs | ec-near-rs | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-ru | ec-near-ru | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-sk | ec-near-sk | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-sy | ec-near-sy | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-tn | ec-near-tn | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-tr | ec-near-tr | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-ua | ec-near-ua | Fixed
1.04 | None | https://iatiregistry.org/dataset/ec-near-xk | ec-near-xk | Fixed
1.05 | n/a | https://iatiregistry.org/dataset/bmub_iki-998 | bmub_iki-998 | Wrong file type
2.01 | n/a | https://iatiregistry.org/dataset/sida-org | sida-org | Wrong file type
2.01 | None | https://iatiregistry.org/dataset/gac-amc-act_2_3 | gac-amc-act_2_3 | XML Error (could not parse)
2.01 | None | https://iatiregistry.org/dataset/said-org | said-org | Validation error
2.02 | n/a | https://iatiregistry.org/dataset/achest-org | achest-org | Wrong file type
2.02 | n/a | https://iatiregistry.org/dataset/dance4life-org | dance4life-org | Wrong file type
2.02 | n/a | https://iatiregistry.org/dataset/friendsofpwyf-activities2 | friendsofpwyf-activities2 | Can't download resource
2.02 | n/a | https://iatiregistry.org/dataset/fwf-org | fwf-org | Wrong file type
2.02 | n/a | https://iatiregistry.org/dataset/ieu-4105 | ieu-4105 | Wrong file type (not set)
2.02 | n/a | https://iatiregistry.org/dataset/max-foundation-org | max-foundation-org | Wrong file type
2.02 | n/a | https://iatiregistry.org/dataset/utz-org | utz-org  | Wrong file type
2.02 | None | https://iatiregistry.org/dataset/alcrer-1-org | alcrer-1-org | Url Error
2.02 | None | https://iatiregistry.org/dataset/bracintl-activities | bracintl-activities | Fixed
2.02 | None | https://iatiregistry.org/dataset/cocnl_publisher-activities | cocnl_publisher-activities | Fixed
2.02 | None | https://iatiregistry.org/dataset/creausa-org-activities | creausa-org-activities | Wrong file type
2.02 | None | https://iatiregistry.org/dataset/fmo-7001_disclosure_overview | fmo-7001_disclosure_overview | Error downloading resource
2.02 | None | https://iatiregistry.org/dataset/freeagirl-bd | freeagirl-bd | Fixed
2.02 | None | https://iatiregistry.org/dataset/freeagirl-in | freeagirl-in | Fixed
2.02 | None | https://iatiregistry.org/dataset/freeagirl-nl | freeagirl-nl | Fixed
2.02 | None | https://iatiregistry.org/dataset/freeagirl-th | freeagirl-th | Fixed
2.02 | None | https://iatiregistry.org/dataset/nl-kvk-54436222-27541-nl | nl-kvk-54436222-27541-nl | Validation error

* Wrong file type: The resource is marked as organization but the xml is activity and vice versa.

* ValidationError example: {'name': [u'Dataset name does not follow the convention publisher-code: "said-org" (using publisher said-uk)']}

* Fixed - we run the archiver again for the ec-near and freegirl publisher.

We have been working on a script that we'll go thorough the publishers and check if the file type and the file match, and correct them if they are wrong. With this we are going to fix the Wrong File Type errors that don't allow a resource to be updated.

**Comment by andylolz** [comment] 2017-10-30 14:37
Great! That explains most of the issues.

> ValidationError example: {'name': [u'Dataset name does not follow the convention publisher-code: "said-org" (using publisher said-uk)']}

I don’t understand this validation error at all. What does it refer to?

> We have been working on a script that we'll go thorough the publishers and check if the file type and the file match, and correct them if they are wrong

So it sounds like you’re saying: auto-update the filetype (Organisation/Activity) in the IATI registry metadata, according to the contents of the file.

I think this would be excellent – as a publisher, I don’t understand why I’m asked to set or manage information about filetype at all. It is just going to cause problems (like the “wrong file type” errors you’re hitting here.)

**Comment by JGulic** [comment] 2017-10-30 15:07
@andylolz the validation error appears because the dataset name is not following the publisher-code, in the above example the resource name should have been: said-uk-org.

And yes, to avoid the 'wrong file type' errors the script will run through the registry and correct the file type according to the resource.

**Comment by andylolz** [comment] 2017-10-30 15:41
> @andylolz the validation error appears because the dataset name is not following the publisher-code, in the above example the resource name should have been: said-uk-org.

Aha! So if I understand correctly, the dataset name should be prefixed by the organisation name? In the case of `said-uk`, the error makes sense. But in the case of `nl-kvk-54436222-27541-nl` and `ec-devco-ec`, I’m not sure what the issue is. But apologies if I’m missing something!

**Comment by JGulic** [comment] 2017-11-01 15:39
@andylolz yes the dataset should be prefixed with the organization name.
In the case od nl-kvk-54436222-27541-nl and ec-devco-ec the problem is that is using part of the organization name. So I am guessing that these datasets were created before this validation has been added to the code.
The validation that does this is [here](https://github.com/ViderumGlobal/ckanext-iati/blob/master/ckanext/iati/logic/validators.py#L81). So ec and nl are in the set and the validation can't pass.

We need to figure out what we are going to do in this case:
1. contact the publishers and tell them to make a change in the name since otherwise the archiver will never update them. For sure we need to contact 'said-uk' 
2. create a solution for the other two organizations, so it can accept the part of the organization name as a name for the dataset (Open a new ticket about this)

**Comment by andylolz** [comment] 2017-11-01 16:03
> The validation that does this is [here](https://github.com/ViderumGlobal/ckanext-iati/blob/master/ckanext/iati/logic/validators.py#L81).

Thanks for linking to the code!

> create a solution for the other two organizations, so it can accept the part of the organization name as a name for the dataset (Open a new ticket about this)

I’ve created ticket #149.

**Comment by andylolz** [comment] 2017-11-07 12:50
> Wrong file type: The resource is marked as organization but the xml is activity and vice versa.

I find it weird that a mistake in the filetype metadata should prevent the version metadata being set. The filetype error should be either flagged or corrected, but the version can be set regardless. I’ve sent a pull request (#151) to do that.

**Comment by goranmaxim** [comment] 2018-02-01 10:45
This has been merged and deployed.

**Comment by dalepotter** [comment] 2018-04-27 10:27
Following work by @goranmaxim and the team at Viderum, this issue is being closed.

If further problems are spotted with this feature, we can open a new issue.

**Closed by dalepotter** 2018-04-27 10:27 UTC
Labels: High priority, bug

**Comment by andylolz** [comment] 2018-04-27 11:18
Looks like there may be some instances where this is still wrong, e.g.: https://iatiregistry.org/dataset/gac-amc-act_2_3
