### ISSUE TITLE
'Last updated date' not updating

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#183] opened 2018-05-15 08:52 UTC
Hi,

A tool provider has got in contact to say that the 'last updated date' for a publisher's dataset is not updating automatically.

Further details are in zendesk ticket #6739

**Comment by andylolz** [comment] 2018-05-15 09:10
Is this a duplicate of #174?

**Comment by derwas** [comment] 2018-05-16 15:16
@amy-silcock  is this still an open issue?

**Comment by dalepotter** [comment] 2018-06-05 16:22
As @andylolz this is a duplicate of #174 and #125 so closing this one...

**Closed by dalepotter** 2018-06-05 16:22 UTC
