### ISSUE TITLE
Cordaid - not all datasets visible for admin user

### ISSUE THREAD

**Issue by andreaszenasidi** [IATI/ckanext-iati#372] opened 2021-09-01 13:21 UTC
The admin user associated with the Cordaid [publisher account](https://iatiregistry.org/publisher/cordaid) doesn't have access to all 5 datasets pubished under the publisher account.

When the admin user logs in to their user account under the Datasets tab they can only see 2 datasets available instead of all 5. The datasets are:
https://iatiregistry.org/dataset/cordaid-005
https://iatiregistry.org/dataset/cordaid-41160054-01

Why can't the admin user see all 5 published datasets?

**Comment by gtkChop** [comment] 2021-09-11 16:02
@andreaszenasidi @jodiegardiner 

Looks like its not a bug:

The dataset tab of the user shows only those datasets that are created by the user.

In this case, we have two users with the same display name

- https://iatiregistry.org/user/cordaid - has 3 datasets
- https://iatiregistry.org/user/shyvonnehenry - has 2 dataset

Looks like the user cordaid is removed from publisher members.

**Comment by PetyaKangalova** [comment] 2021-09-13 10:28
@gtkChop thanks for the update. I  am following up with the user to explain about the two accounts. The issue here is that the same email was used for both user accounts (which if obviously confusing for the user). Could I check if the Registry still allows multiple users with the same email address?

**Comment by PetyaKangalova** [comment] 2021-09-15 13:38
Closing this issue as it has now been resolved. Currently users can create multiple accounts with same email. To create a separate issue if we want to change.

**Closed by PetyaKangalova** 2021-09-15 13:38 UTC
Labels: High priority, Needs Testing
