### ISSUE TITLE
Bug - first published date being reset

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#240] opened 2019-03-05 10:01 UTC
Please the end of the discussion thread here: https://discuss.iatistandard.org/t/iati-data-licensing-for-unencumbered-data-use/1651/17

UNOPS have recently changed their licensing type, and doing so re-set their first published date. Please can you look into the ASAP and make sure changing the licensing type (and other fields) doesn't reset publisher's first published date.

**Comment by andylolz** [comment] 2019-03-05 10:30
Reproducing [this comment](https://github.com/IATI/ckanext-iati/issues/232#issuecomment-469355523) here:

> Why doesn’t [the first published date] always come from the earliest resource `metadata_created` date? Why allow the publisher to create or edit it?
> 
> The [UNOPS publisher page](https://iatiregistry.org/publisher/unops) says they first published on 29 August 2018. However, their earliest resource `metadata_created` date is 3 October 2011. And in fact, the `publisher_first_publish_date` in the metadata says "03.10.2011" which (notwithstanding being a weird and ambiguous way to store a date) is correct. Where has 29 August 2018 come from?

It’s trivial to produce a list of publishers by first published date, using their earliest resource `metadata_created`. See:
https://gist.github.com/andylolz/733eb303fb6a952521b611f17fe91961

I mention this because it seems to go wrong quite often. Perhaps simplifying it would make it more robust.

**Comment by gtkChop** [comment] 2019-03-05 12:31
@amy-silcock 

Hi Amy I tried to reproduce the error - however, I don't see changing license affecting first_published_date. Could you please give more detail on reproducing this error? Thanks

**Comment by gtkChop** [comment] 2019-03-06 11:15
I was unable to reproduce this error in staging and prod.

I believe this might have been caused one of two ways:
•    Browser auto-fill feature
•    A mistake made when changing the publisher id

I have tried to reproduce the error by changing the license type and several meta fields and first published date remains the same as before (it does not reset to any default value).

If this error recurs, please notify us again and we will look into it as a high priority.

**Comment by amy-silcock** [comment] 2019-03-08 12:18
Hi Swaroop,

This has also happened for the Danish ministry: 

I notice that the information on ’first published date’ has been reset to something wrong again – it should read 19. March 2012.

 
![image](https://user-images.githubusercontent.com/27764077/54028210-3916a600-419c-11e9-9b73-871d63f263c7.png)



You are are copied in to the message with the publisher.

**Comment by andylolz** [comment] 2019-03-08 13:04
[UK Home Office](https://iatiregistry.org/publisher/hooda) says:

> First published date:
> 01 November 2018

**Comment by andylolz** [comment] 2019-03-08 13:05
[Germany - Ministry for Economic Cooperation and Development publisher page](https://iatiregistry.org/publisher/bmz) says:

> First published date:
> 06 December 2018

**Comment by gtkChop** [comment] 2019-03-08 13:07
I will go through the logs in database and UI and get back to you on this shortly. Thanks

**Comment by gtkChop** [comment] 2019-03-11 12:13
It looks like the problem is due to functionality that tries to patch the ‘first published date’ and ‘publisher contact email’ to ‘please@update.com’ if they are blank. This occurs when a read of the page is taking place by an Admin, which means the user will not be aware that the change is occurring. Because of an existing bug, it looks like the ‘first published date’ is overwritten sometimes, even if the value is not blank.
We will update the functionality so that it does not overwrite existing values.

Current Functionality
first published date is blank - data is automatically overwritten when the page is being read
first published date is not blank - data is sometimes automatically overwritten when the page is being read

Suggested Fix
first published date is blank - data is automatically overwritten with resource first publish date by Archiver
first published date is not blank - never automatically overwrite.

https://github.com/IATI/ckanext-iati/issues/161

According to the above link. Could you please provide us the external list, please. Thanks

**Comment by JoshStanleyDevInit** [comment] 2019-03-12 10:12
Hi Swaroop,

We are happy with your suggested fix. This should ensure that in the future the First Published Date is only populated with the date that the organisation has actually first published.

However, we have a question around organisations that currently have a blank first published date? Please can you advise which organisations these are? We would not expect organisations to have published to not have this field populated.

Josh

**Comment by gtkChop** [comment] 2019-03-13 12:52
Yes, an organization can have an empty first published date:

There are total of 196 publishers with first published date empty. These are the few eg- of a publisher with an empty date. 

https://iatiregistry.org/publisher/mazarsllp
https://iatiregistry.org/publisher/gtc
https://iatiregistry.org/publisher/aid_works
https://iatiregistry.org/publisher/lts
https://iatiregistry.org/publisher/trimpact

Conditions when first_published date can be empty:
- When the publisher never published a  resource i.e no dataset.
- when all the dataset under that publisher is private.
On these two conditions first_published_date would be empty. This is the expected behavior.

Previous functionality:
First_published date was not a mandatory field, so the user had the option to leave this field blank. The current system updates (writing to db) this field with the earliest resource creation date during a *read* operation.  This is unexpected behavior and has lead to data corruption. 

Suggested functionality:
If the first published date is blank or missing, display the first resource creation date (not writing to DB during a read operation). When a user updates their publisher page, the system can add their first published date if it does not already exist. This avoids any data corruption issues.

**Comment by gtkChop** [comment] 2019-06-04 14:28
Updated first published date - here is report


Please see the evaluation metrics below - 

Total Number of publisher given: 958
Number of the organization not found: 4 (organization not found)
Organization update failed: 75


Failed to update 75 organization is due to following reasons - 
Missing email address
Not a valid email address.

**Comment by gtkChop** [comment] 2019-06-07 11:51
Updated all first published date - 
Added a new cron job to capture date if not updated.

**Comment by gtkChop** [comment] 2019-06-17 08:42
The cron job is running on a daily basis. Closing the ticket. Please reopen if there are any issues. Thanks

**Closed by gtkChop** 2019-06-17 08:42 UTC
Labels: High priority, bug
