### ISSUE TITLE
First published date being reset 

### ISSUE THREAD

**Issue by dalepotter** [IATI/ckanext-iati#161] opened 2018-01-26 12:12 UTC
As reported by @amy-silcock, it appears that the first published date for [Denmark - Ministry of Foreigh Affairs](https://www.iatiregistry.org/publisher/danida) has been reset to `22 December 2017` when they have been publishing for a lot longer: 

![image](https://user-images.githubusercontent.com/8247168/35438971-c6858be2-0290-11e8-9b16-9e10586da9cb.png)

Note that this publisher has recently changed it's organisation identifier (from `DK-1` to `XM-DAC-3-1`), which may be useful information to support investigations.

An identical issue affecting the [Catholic Agency For Overseas Development (CAFOD)](https://www.iatiregistry.org/publisher/cafod) was reported in Zendesk issue #6302, but amended manually.

The issue was also reported to affect the [Belgian development agency (Enabel)](https://www.iatiregistry.org/publisher/enabel) (who changed their Registry publisher ID to `enabel`, but org ID remained the same). I have been able to find any further information about this issue.

I will mark this is a bug.

**Comment by andylolz** [comment] 2018-01-29 11:00
[It says 19 March 2012.](https://www.iatiregistry.org/publisher/danida) Was this updated manually?

**Comment by amy-silcock** [comment] 2018-01-29 15:33
@andylolz  Yes I updated it manually for Denmark - Ministry of Foreign Affairs

**Comment by andylolz** [comment] 2018-01-29 18:05
The relevant code is not very clear:
https://github.com/ViderumGlobal/ckanext-iati/blob/3a54efa7f4c0efd49eee6c459c0fdf05a7953068/ckanext/iati/helpers.py#L288-L342

**Comment by newkdukem** [comment] 2018-02-07 15:59
This issue is currently under investigation. We'll post our findings as soon as we pinpoint the root cause.

**Comment by newkdukem** [comment] 2018-03-07 13:34
I was unable to reproduce the issue locally. I changed the organisation identifier but the first published date value did not reset. 
However I have made a [refactor](https://github.com/ViderumGlobal/ckanext-iati/pull/163) on the code @andylolz have mentioned earlier, so that functionality will be more clear in the future.

**Comment by derwas** [comment] 2018-06-07 19:16
The relevant code highlighted by @andylolz is the one responsible for this issue.

The reasons is because simply the code does the following: loop through the packages(datasets) of an organization (L311) and collect their creation dates (L317) in dates [] (variable declared in L295). The first published date is the the first element of the sorted list of dates.

In other words, this date is automatically calculated based on the oldest date that appears in the datasets of that organization. As long as the oldest dataset exists this information will remain the same.

**Comment by andylolz** [comment] 2018-06-08 09:43
Worth noting that this function was cleaned up a bit, in some commits that aren’t on the derilinx fork. It even includes some explanation at the top now, which matches up with @derwas’ assessment:
https://github.com/IATI/ckanext-iati/blob/7debfc7b69305e6aa37e58f8b08fcdad989f7e5e/ckanext/iati/helpers.py#L287-L291

**Comment by amy-silcock** [comment] 2018-11-01 16:11
This is now fixed

**Comment by amy-silcock** [comment] 2018-11-01 16:11
All first published dates have been corrected, according to external list.

**Closed by amy-silcock** 2018-11-01 16:11 UTC
Labels: bug
